version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: 'Dockerfile-${DB_TYPE}'
      args:
        db_name: ${DB_NAME}
        db_user: ${DB_USER}
        db_password: ${DB_PASSWORD}
        db_port: ${DB_PORT}
    restart: always
    volumes:
      - type: volume
        source: ${DB_OUTSIDE_VOLUME}
        target: ${DB_INSIDE_VOLUME}
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - '${DB_PORT}:${DB_PORT}'


  metabase:
    image: metabase/metabase
    restart: always
    environment:
      MB_DB_FILE: '${MB_DB_FILE}'
      MB_DB_TYPE: '${DB_TYPE}'
      MB_DB_DBNAME: '${DB_NAME}'
      MB_DB_PORT: '${DB_PORT}'
      MB_DB_USER: '${DB_USER}'
      MB_DB_HOST: 'db'
      MB_DB_PASS: '${DB_PASSWORD}'
      JAVA_TIMEZONE: '${MB_JAVA_TIMEZONE}'
    ports:
      - '${MB_PORT}:3000'
    volumes:
      - 'mb-data:/metabase-data'
    depends_on:
      - 'db'

volumes:
  db-data:
  mb-data:
